name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Pip Install
        run: pip3 install -r requirements.txt

      - name: NPM Install
        run: cd highlighter && npm install

      - name: Build
        run: |
          export TZ="America/Los_Angeles"
          shopt -s globstar
          python3 -m md2html 404.md index.md blog/**/*.md
          sed -i "/html/d" .gitignore

      # Fixes issue where LFS metadata files are pushed to gh-pages branch, not
      # the files themselves.
      - name: Disable LFS
        run: |
          rm -rf .gitattributes
          git lfs uninstall

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: .
          single-commit: true
