name: tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: NPM install
        run: cd highlighter && npm i

      - name: Pip install
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Flake8
        run: flake8

      - name: Mypy
        run: mypy -p md2html

      - name: Black
        run: black md2html test --check --diff --color -l 79

      - name: Pytest
        run: pytest --cov=$PWD --cov-report term --cov-report html
