name: tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: NPM install
        run: cd highlighter && npm i

      - name: Pip install
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Typos
        run: make typos

      - name: Ruff
        run: make ruff

      - name: Mypy
        run: make mypy

      - name: Black
        run: make black

      - name: Pytest
        run: make pytest

      - name: Refurb
        run: make refurb
